#pragma once

#include <cstdint>
#include <cstring>
#include <memory>
#include <string>

namespace ssea
{
    // -----------------------------------------------------------------------------
    // Scalar reference implementation: 1:1 port of ppp/cryptography/ssea.cpp
    // base94_encode / base94_decode (semantics of the openppp2 ssea module).
    // Used as the correctness baseline for the SIMD variants.
    // -----------------------------------------------------------------------------

    constexpr int BASE94_SYMBOL_COUNT = 94;   ///< Number of symbols in Base94 alphabet
    constexpr int BASE94_INPUT_BLOCK_SIZE = 9; ///< Optimal input block size (bytes)
    constexpr int BASE94_OUTPUT_BLOCK_SIZE = 11; ///< Optimal output block size (chars)
    constexpr int BASE93_RADIX = BASE94_SYMBOL_COUNT - 1; ///< 93

    /**
     * @brief Encodes binary bytes with the project-specific Base94 mapping.
     * @param data    Input bytes (must be non-null, datalen >= 1).
     * @param datalen Number of input bytes.
     * @param kf      Per-byte offset subtracted before mapping.
     * @param output  [out] Receives the allocated encoded buffer.
     * @return Encoded byte count, or 0 on failure.
     */
    inline int base94_encode_scalar(const void* data, int datalen, int kf, std::unique_ptr<uint8_t[]>& output) noexcept
    {
        const uint8_t* bytes = static_cast<const uint8_t*>(data);
        if (nullptr == bytes || datalen < 1)
        {
            return 0;
        }

        // First pass: compute the length of the encoded string.
        int bucket_length = 0;
        for (int i = 0; i < datalen; i++)
        {
            const uint8_t b = static_cast<uint8_t>(bytes[i] - kf);
            bucket_length += (b >= BASE93_RADIX) ? 2 : 1;
        }

        output = std::make_unique<uint8_t[]>(bucket_length + 16); // +16 slack for SIMD-safe writes
        uint8_t* bucket = output.get();
        for (int i = 0; i < datalen; i++)
        {
            const uint8_t b = static_cast<uint8_t>(bytes[i] - kf);
            if (b >= BASE93_RADIX)
            {
                *bucket++ = static_cast<uint8_t>('\x20' + (((b / BASE93_RADIX) - 1) + BASE93_RADIX));
                *bucket++ = static_cast<uint8_t>('\x20' + (b % BASE93_RADIX));
            }
            else
            {
                *bucket++ = static_cast<uint8_t>('\x20' + b);
            }
        }

        return bucket_length;
    }

    /**
     * @brief Decodes bytes generated by base94_encode_scalar.
     * @param data    Encoded Base94 byte sequence.
     * @param datalen Number of encoded input bytes.
     * @param kf      Per-byte offset added back after decoding.
     * @param output  [out] Receives the allocated decoded buffer.
     * @return Decoded byte count, or 0 on failure (invalid input).
     */
    inline int base94_decode_scalar(const void* data, int datalen, int kf, std::unique_ptr<uint8_t[]>& output) noexcept
    {
        const uint8_t* bytes = static_cast<const uint8_t*>(data);
        if (nullptr == bytes || datalen < 1)
        {
            return 0;
        }

        // First pass: validate input and compute output length.
        int bucket_length = datalen;
        for (int i = 0; i < datalen; i++)
        {
            uint8_t b = bytes[i];
            if (b < '\x20')
            {
                return 0;   // Character below printable range
            }

            b -= '\x20';
            if (b > BASE94_SYMBOL_COUNT)
            {
                return 0;   // Character beyond the 94 symbols
            }

            if (b >= BASE93_RADIX)
            {
                // Two-character escape; next character must exist.
                if (++i < datalen)
                {
                    b = bytes[i];
                    if (b < '\x20')
                    {
                        return 0;
                    }

                    b -= '\x20';
                    if (b > BASE93_RADIX)
                    {
                        return 0;
                    }
                }
                else
                {
                    return 0;   // Unexpected end of string
                }

                bucket_length--;
            }
        }

        output = std::make_unique<uint8_t[]>(bucket_length + 16);
        uint8_t* bucket = output.get();
        for (int i = 0; i < datalen; i++)
        {
            const uint8_t b = bytes[i] - '\x20';
            if (b >= BASE93_RADIX)
            {
                const int v = (((b - BASE93_RADIX) + 1) * BASE93_RADIX) + (bytes[++i] - '\x20');
                if (v > 0xff)
                {
                    return 0;   // Decoded value out of byte range
                }

                *bucket++ = static_cast<uint8_t>(v + kf);
            }
            else
            {
                *bucket++ = static_cast<uint8_t>(b + kf);
            }
        }

        return bucket_length;
    }

    // -----------------------------------------------------------------------------
    // Scalar references for the remaining ssea primitives (1:1 ports of ssea.cpp).
    // -----------------------------------------------------------------------------

    /**
     * @brief Produces a pseudo-random 31-bit integer and advances the seed.
     * @param seed Seed pointer modified in place.
     * @return Generated pseudo-random value.
     */
    inline int random_next_scalar(unsigned int* seed) noexcept
    {
        unsigned int next = *seed;
        int result;

        next *= 1103515245;
        next += 12345;
        result = (unsigned int)(next / 65536) % 2048;

        next *= 1103515245;
        next += 12345;
        result <<= 10;
        result ^= (unsigned int)(next / 65536) % 1024;

        next *= 1103515245;
        next += 12345;
        result <<= 10;
        result ^= (unsigned int)(next / 65536) % 1024;

        *seed = next;
        return result;
    }

    /**
     * @brief Delta-encodes a byte sequence: out[0] = in[0] - kf; out[i] = in[i] - in[i-1].
     * @param data      Input bytes (data_size >= 1).
     * @param data_size Number of input bytes.
     * @param kf        Initial adjustment for the first byte.
     * @param output    [out] Encoded buffer.
     * @return data_size on success, 0 on failure.
     */
    inline int delta_encode_scalar(const void* data, int data_size, int kf, std::unique_ptr<uint8_t[]>& output) noexcept
    {
        const uint8_t* bytes = static_cast<const uint8_t*>(data);
        if (nullptr == bytes || data_size < 1)
        {
            return 0;
        }

        output = std::make_unique<uint8_t[]>(data_size + 16);
        uint8_t* p = output.get();
        *p++ = static_cast<uint8_t>(*bytes++ - kf);
        while (--data_size > 0)
        {
            *p++ = static_cast<uint8_t>(*bytes - *(bytes - 1));
            bytes++;
        }

        return static_cast<int>(p - output.get());
    }

    /**
     * @brief Delta-decodes: out[0] = in[0] + kf; out[i] = out[i-1] + in[i].
     * @param data      Delta-encoded bytes (data_size >= 1).
     * @param data_size Number of input bytes.
     * @param kf        Initial adjustment used at encode time.
     * @param output    [out] Decoded buffer.
     * @return data_size on success, 0 on failure.
     */
    inline int delta_decode_scalar(const void* data, int data_size, int kf, std::unique_ptr<uint8_t[]>& output) noexcept
    {
        const uint8_t* bytes = static_cast<const uint8_t*>(data);
        if (nullptr == bytes || data_size < 1)
        {
            return 0;
        }

        output = std::make_unique<uint8_t[]>(data_size + 16);
        uint8_t* p = output.get();
        *p++ = static_cast<uint8_t>(*bytes++ + kf);
        while (--data_size > 0)
        {
            *p = static_cast<uint8_t>(*(p - 1) + *bytes);
            p++;
            bytes++;
        }

        return static_cast<int>(p - output.get());
    }

    /**
     * @brief Applies a fixed XOR mask to a memory range (32/16/8-bit chunks).
     * @param min Inclusive start address.
     * @param max Exclusive end address.
     * @param kf  Fixed 32-bit XOR key.
     * @return true on success, false when the range is invalid.
     */
    inline bool masked_xor_scalar(const void* min, const void* max, int32_t kf) noexcept
    {
        const int length = static_cast<int>(static_cast<const uint8_t*>(max) - static_cast<const uint8_t*>(min));
        if (0 == length)
        {
            return true;
        }
        if (length < 0)
        {
            return false;
        }

        int count     = length >> 2;
        int remainder = length & 3;

        int32_t* p32 = const_cast<int32_t*>(static_cast<const int32_t*>(min));
        for (int i = 0; i < count; i++)
        {
            *p32 = *p32 ^ kf;
            p32++;
        }

        int16_t* p16 = reinterpret_cast<int16_t*>(p32);
        if (remainder >> 1)
        {
            *p16 = static_cast<int16_t>(*p16 ^ kf);
            p16++;
        }

        int8_t* p8 = reinterpret_cast<int8_t*>(p16);
        if (remainder & 1)
        {
            *p8 = static_cast<int8_t>(*p8 ^ kf);
        }

        return true;
    }

    /**
     * @brief Applies a per-word LCG keystream XOR to a memory range.
     * @param min Inclusive start address.
     * @param max Exclusive end address.
     * @param kf  Initial key factor (LCG seed).
     * @return true on success, false when the range is invalid.
     */
    inline bool masked_xor_random_next_scalar(const void* min, const void* max, int32_t kf) noexcept
    {
        const int length = static_cast<int>(static_cast<const uint8_t*>(max) - static_cast<const uint8_t*>(min));
        if (0 == length)
        {
            return true;
        }
        if (length < 0)
        {
            return false;
        }

        int count     = length >> 2;
        int remainder = length & 3;

        kf = random_next_scalar(reinterpret_cast<unsigned int*>(&kf));

        int32_t* p32 = const_cast<int32_t*>(static_cast<const int32_t*>(min));
        for (int i = 0; i < count; i++)
        {
            *p32 = *p32 ^ kf;
            p32++;
            kf = random_next_scalar(reinterpret_cast<unsigned int*>(&kf));
        }

        int16_t* p16 = reinterpret_cast<int16_t*>(p32);
        if (remainder >> 1)
        {
            *p16 = static_cast<int16_t>(*p16 ^ kf);
            p16++;
        }

        int8_t* p8 = reinterpret_cast<int8_t*>(p16);
        if (remainder & 1)
        {
            *p8 = static_cast<int8_t>(*p8 ^ kf);
        }

        return true;
    }

    /**
     * @brief Permutes bytes in place using the (i ^ key) % size permutation.
     * @param encoded_data Mutable target buffer.
     * @param data_size    Number of bytes.
     * @param key          Permutation key.
     */
    inline void shuffle_data_scalar(char* encoded_data, int data_size, uint32_t key) noexcept
    {
        if (nullptr != encoded_data && data_size > 0)
        {
            for (int i = 0; i < data_size; i++)
            {
                const uint32_t p = static_cast<uint32_t>(i);
                const uint32_t j = static_cast<uint32_t>((p ^ key) % static_cast<uint32_t>(data_size));
                std::swap(encoded_data[i], encoded_data[j]);
            }
        }
    }

    /**
     * @brief Reverses shuffle_data_scalar for the same key and size.
     * @param encoded_data Mutable target buffer.
     * @param data_size    Number of bytes.
     * @param key          Permutation key used originally.
     */
    inline void unshuffle_data_scalar(char* encoded_data, int data_size, uint32_t key) noexcept
    {
        if (nullptr != encoded_data && data_size > 0)
        {
            for (int i = data_size - 1; i > -1; i--)
            {
                const uint32_t p = static_cast<uint32_t>(i);
                const uint32_t j = static_cast<uint32_t>((p ^ key) % static_cast<uint32_t>(data_size));
                std::swap(encoded_data[i], encoded_data[j]);
            }
        }
    }

    // -----------------------------------------------------------------------------
    // base94_decimal: compact integer <-> Base94 string conversion.
    //
    // SIMD FEASIBILITY ARGUMENT (why these stay scalar):
    //   * uint64 -> string: a SERIAL chain of 64-bit divisions by 94 (at most 11
    //     iterations); every digit depends on the previous remainder. SSE2 has no
    //     64-bit integer division, and the dependency chain cannot be parallelized.
    //     The entire input/output is 8..11 bytes - SIMD setup alone exceeds the
    //     total work.
    //   * string -> uint64: a SERIAL multiply-add chain (n = n*94 + digit, 11
    //     steps), each step depending on the previous. No parallel form exists;
    //     the input is at most 11 bytes.
    //   * There is no production batch scenario (one integer per packet header),
    //     so SIMD amortization is impossible.
    //   * CONCLUSION: SIMD is NOT applicable to base94_decimal on both algorithmic
    //     (serial dependency, no 64-bit SIMD division) and economic (tiny data)
    //     grounds. Scalar is the correct and only reasonable choice.
    // -----------------------------------------------------------------------------

    /**
     * @brief Decodes Base94 bytes into an unsigned 64-bit integer.
     * @param data    Base94 byte sequence (chars 0x20..0x7D, i.e. offsets 0..93).
     * @param datalen Number of bytes.
     * @return Parsed integer, or 0 for invalid input (chars below 0x20 or >= 94).
     */
    inline uint64_t base94_decimal_scalar(const void* data, int datalen) noexcept
    {
        const uint8_t* p = static_cast<const uint8_t*>(data);
        if (nullptr == p || datalen < 1)
        {
            return 0;
        }

        uint64_t n = 0;
        for (const uint8_t* k = p + datalen; p != k;)
        {
            uint8_t b = *p++;
            if (b < '\x20')
            {
                return 0;   // below printable range
            }
            b -= '\x20';
            if (b >= BASE94_SYMBOL_COUNT)
            {
                return 0;   // beyond the 94 symbols
            }
            n = n * BASE94_SYMBOL_COUNT + b;
        }
        return n;
    }

    /**
     * @brief Decodes a Base94 std::string into an unsigned 64-bit integer.
     * @param v Base94 text.
     * @return Parsed integer, or 0 for invalid input.
     */
    inline uint64_t base94_decimal_scalar(const std::string& v) noexcept
    {
        return base94_decimal_scalar(v.data(), static_cast<int>(v.size()));
    }

    /**
     * @brief Encodes an unsigned 64-bit integer as its minimal Base94 string.
     * @param v Integer value.
     * @return Base94 representation (no null terminator), minimal length (<= 11).
     */
    inline std::string base94_decimal_scalar(uint64_t v) noexcept
    {
        int base94_size = 0;
        uint8_t base94[BASE94_OUTPUT_BLOCK_SIZE];   // 94^11 > 2^64, so 11 chars suffice
        {
            uint64_t n = v;
            do
            {
                n /= BASE94_SYMBOL_COUNT;
                base94_size++;
            } while (n > 0);

            int k = 0;
            n = v;
            do
            {
                const uint8_t c = static_cast<uint8_t>((n % BASE94_SYMBOL_COUNT) + '\x20');
                n /= BASE94_SYMBOL_COUNT;
                base94[(base94_size) - (++k)] = c;   // store least-significant first, then reverse
            } while (n > 0);
        }

        return std::string(reinterpret_cast<char*>(base94), base94_size);
    }

    /**
     * @brief Produces a pseudo-random integer in the inclusive range [min, max].
     * @param seed Seed pointer modified in place.
     * @param min  Inclusive lower bound.
     * @param max  Inclusive upper bound.
     * @return Random integer in [min, max].
     */
    inline int random_next_scalar(unsigned int* seed, int min, int max) noexcept
    {
        const int v = random_next_scalar(seed);
        return v % (max - min + 1) + min;
    }

    /**
     * @brief Convenience wrapper: maps a key factor through random_next in [min, max].
     * @param kf  32-bit key factor reinterpreted as the PRNG seed (advanced in place).
     * @param min Inclusive lower bound.
     * @param max Inclusive upper bound.
     * @return Pseudo-random integer in [min, max].
     */
    inline int lcgmod_scalar(int32_t kf, int min, int max) noexcept
    {
        return random_next_scalar(reinterpret_cast<unsigned int*>(&kf), min, max);
    }
}
